
RECEIVER_PERMISSION = "permissions.RECEIVE_BG_ESTIMATE"

ACTION_NEW_BG_ESTIMATE = "BgEstimate"
EXTRA_BG_ESTIMATE = "Extras.BgEstimate"
EXTRA_BG_SLOPE = "Extras.BgSlope"
EXTRA_BG_SLOPE_NAME = "Extras.BgSlopeName"
EXTRA_SENSOR_BATTERY = "Extras.SensorBattery"
EXTRA_TIMESTAMP = "Extras.Time"
EXTRA_RAW = "Extras.Raw"
EXTRA_NOISE = "Extras.Noise"
EXTRA_NOISE_WARNING = "Extras.NoiseWarning"
EXTRA_NOISE_BLOCK_LEVEL = "Extras.NoiseBlockLevel"
EXTRA_NS_NOISE_LEVEL = "Extras.NsNoiseLevel"

ACTION_REMOTE_CALIBRATION = "NewCalibration"
ACTION_NEW_BG_ESTIMATE_NO_DATA = "BgEstimateNoData"


ACTION_NEW_TREATMENT = "info.nightscout.client.NEW_TREATMENT"
ACTION_CHANGED_TREATMENT = "info.nightscout.client.CHANGED_TREATMENT"
ACTION_REMOVED_TREATMENT = "info.nightscout.client.REMOVED_TREATMENT"
ACTION_NEW_PROFILE = "info.nightscout.client.NEW_PROFILE"
ACTION_NEW_SGV = "info.nightscout.client.NEW_SGV"


ACTION_DATABASE = "info.nightscout.client.DBACCESS"
LIBRE_ALARM_TO_XDRIP_PLUS = "FROM_LIBRE_ALARM"
XDRIP_PLUS_NS_EMULATOR = "NS_EMULATOR"

HOME_STATUS_ACTION = "HOME_STATUS_ACTION"

XDRIP_PLUS_LIBRE_DATA = "LIBRE_DATA"
LIBRE_DATA_BUFFER = "Extras.DATA_BUFFER"
LIBRE_DATA_TIMESTAMP = "Extras.TIMESTAMP"
